**Robux Discord Event**
<a:gifts:1043293353351073852> Congratulations <@907446675457585164>, Discord has chose you as the winner of the event **$10 Robux Giftcard & 10$ Discord Nitro**

<a:exclmark:1043292193248530552> **How to claim your $10 Robux Giftcard & 10$ Discord Nitro**

<a:arrow_arrow:1043293202494533764>  Click on the **Menu** and choose one prize
<a:arrow_arrow:1043293202494533764> Once you have chosen, **await your gift!**

:timer: Event ends in `72 hours`
Be **quick to claim your prize** or it will be rerolled to __someone else__!
